### ISSUE TITLE
[NcDialog] Cannot read properties of undefined (reading 'mounted')

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-vue#5296]
cc @susnux 

```js
TypeError: Cannot read properties of undefined (reading 'mounted')
    at injectHook (vue.runtime.esm.js:3320:1)
    at vue.runtime.esm.js:3306:1
    at useMounted (index.mjs:501:1)
    at useSupported (index.mjs:509:1)
    at useResizeObserver (index.mjs:2518:1)
    at useElementSize (index.mjs:2676:1)
    at setup (NcDialog-652A8lMI.mjs:158:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:3033:1)
    at initSetup (vue.runtime.esm.js:2457:1)
    at initState (vue.runtime.esm.js:5385:1)
logError @ vue.runtime.esm.js:3065
globalHandleError @ vue.runtime.esm.js:3057
handleError @ vue.runtime.esm.js:3024
invokeWithErrorHandling @ vue.runtime.esm.js:3040
initSetup @ vue.runtime.esm.js:2457
initState @ vue.runtime.esm.js:5385
Vue._init @ vue.runtime.esm.js:5714
VueComponent @ vue.runtime.esm.js:5849
createComponentInstanceForVnode @ vue.runtime.esm.js:4564
init @ vue.runtime.esm.js:4426
createComponent @ vue.runtime.esm.js:6591
createElm @ vue.runtime.esm.js:6545
patch @ vue.runtime.esm.js:7133
Vue._update @ vue.runtime.esm.js:3785
updateComponent @ vue.runtime.esm.js:3891
Watcher.get @ vue.runtime.esm.js:3462
Watcher.run @ vue.runtime.esm.js:3538
flushSchedulerQueue @ vue.runtime.esm.js:4141
(anonymous) @ vue.runtime.esm.js:3159
flushCallbacks @ vue.runtime.esm.js:3081
Promise.then (async)
timerFunc @ vue.runtime.esm.js:3106
nextTick @ vue.runtime.esm.js:3171
queueWatcher @ vue.runtime.esm.js:4227
Watcher.update @ vue.runtime.esm.js:3529
Dep.notify @ vue.runtime.esm.js:732
reactiveSetter @ vue.runtime.esm.js:967
proxySetter @ vue.runtime.esm.js:5376
click @ Users.vue:193
invokeWithErrorHandling @ vue.runtime.esm.js:3033
invoker @ vue.runtime.esm.js:1832
invokeWithErrorHandling @ vue.runtime.esm.js:3033
Vue.$emit @ vue.runtime.esm.js:3732
onClick @ NcAppNavigationItem-A1yAdDNN.mjs:418
click @ NcAppNavigationItem-A1yAdDNN.mjs:480
invokeWithErrorHandling @ vue.runtime.esm.js:3033
invoker @ vue.runtime.esm.js:1832
original_1._wrapper @ vue.runtime.esm.js:7500
12:10:02.154 
```

**Comment by susnux** [comment]
This is causes by `@vueuse/component` being updated to `1.8.0` (you updated that on server?).
1.8.0 has a regression with Vue 2, they already fixed that but it is still unreleased:
https://github.com/vueuse/vueuse/pull/3802

**Comment by skjnldsv** [comment]
Damn, we should revert then
